global:
  scrape_interval:     2s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 1s # Evaluate rules every 15 seconds. The default is every 1 minute.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['127.0.0.1:9090']
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    scrape_timeout: 1s
    static_configs:
    - targets: ['172.17.0.1:8080']
      labels:
        app: 'db-test'
  - job_name: 'blackbox'
    scrape_interval: 2s
    scrape_timeout: 1s
    metrics_path: /probe
    params:
      module: [http_localhost]
    static_configs:
      - targets: ['http://172.17.0.1:8080/actuator/health']
      - targets: ['http://172.17.0.1:8080/actuator/health/ping']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
